const FETCH_TODOS_REQUEST = "FETCH_TODOS_REQUEST";
const FETCH_TODOS_FAILED = "FETCH_TODOS_FAILED";
const FETCH_TODOS_SUCCESS = "FETCH_TODOS_SUCCESS";
const FETCH_TODOS_CLEAR = "FETCH_TODOS_CLEAR";

const ADD_TODO_REQUEST = "ADD_TODO_REQUEST";
const ADD_TODO_FAILED = "ADD_TODO_FAILED";
const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
const ADD_TODO_CLEAR = "ADD_TODO_CLEAR";
