export const FETCH_TODOS_REQUEST = "FETCH_TODOS_REQUEST";
export const FETCH_TODOS_FAILED = "FETCH_TODOS_FAILED";
export const FETCH_TODOS_SUCCESS = "FETCH_TODOS_SUCCESS";
export const FETCH_TODOS_CLEAR = "FETCH_TODOS_CLEAR";

export const ADD_TODO_REQUEST = "ADD_TODO_REQUEST";
export const ADD_TODO_FAILED = "ADD_TODO_FAILED";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_CLEAR = "ADD_TODO_CLEAR";

export const EDIT_TODO_REQUEST = "ADD_TODO_REQUEST";
export const EDIT_TODO_FAILED = "ADD_TODO_FAILED";
export const EDIT_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const EDIT_TODO_CLEAR = "ADD_TODO_CLEAR";
