export const FETCH_TODOS_REQUEST = "FETCH_TODOS_REQUEST";
export const FETCH_TODOS_FAILED = "FETCH_TODOS_FAILED";
export const FETCH_TODOS_SUCCESS = "FETCH_TODOS_SUCCESS";
export const FETCH_TODOS_CLEAR = "FETCH_TODOS_CLEAR";

export const ADD_TODO_REQUEST = "ADD_TODO_REQUEST";
export const ADD_TODO_FAILED = "ADD_TODO_FAILED";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_CLEAR = "ADD_TODO_CLEAR";

export const EDIT_TODO_REQUEST = "EDIT_TODO_REQUEST";
export const EDIT_TODO_FAILED = "EDIT_TODO_FAILED";
export const EDIT_TODO_SUCCESS = "EDIT_TODO_SUCCESS";
export const EDIT_TODO_CLEAR = "EDIT_TODO_CLEAR";

export const REMOVE_TODO = {
  REQUEST: "REMOVE_TODO_REQUEST",
  FAILED: "REMOVE_TODO_FAILED",
  SUCCESS: "REMOVE_TODO_SUCCESS",
  CLEAR: "REMOVE_TODO_CLEAR",
};
export const SELECT_TODO = {
  REQUEST: "SELECT_TODO_REQUEST",
  FAILED: "SELECT_TODO_FAILED",
  SUCCESS: "SELECT_TODO_SUCCESS",
  CLEAR: "SELECT_TODO_CLEAR",
};

export const ITEMS_TODO = {
  REQUEST: "ITEMS_TODO_REQUEST",
  FAILED: "ITEMS_TODO_FAILED",
  SUCCESS: "ITEMS_TODO_SUCCESS",
  CLEAR: "ITEMS_TODO_CLEAR",
};
